"use client";

import { CheckCircle2, Copy, Plus, Share2, ShoppingCart, Trash2 } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useMemo, useState, useTransition } from "react";

import SearchableCombobox from "@/components/ui/SearchableCombobox";
import { addEventGroceryItem, removeEventGroceryItem, updateEventGroceryItem } from "@/lib/event-grocery/actions";
import { createEventGroceryCheckoutSession } from "@/lib/grocery/checkoutSessions";

const units = ["kg", "g", "litre", "ml", "packet", "box", "bottle", "piece", "dozen"] as const;
type Unit = typeof units[number];
type CatalogItem = { id: string; name: string };
type ListItem = { id: string; catalogItemId: string; name: string; quantity: number; unit: Unit };

function shareText(name: string, items: ListItem[], purchase: Purchase | null) {
  const purchaseSummary = purchase ? `✓ Purchased via ${purchase.providerName}\n${new Intl.DateTimeFormat("en-IN", { day: "numeric", month: "short", year: "numeric" }).format(new Date(purchase.completedAt))}\n\n` : "";
  return `${name} - Grocery List\n\n${purchaseSummary}${items.map((item) => `${item.name} - ${item.quantity} ${item.unit}`).join("\n")}`;
}

type Purchase = { providerName: string; completedAt: string; itemCount: number };

export default function EventGroceryListEditor({ listId, name, catalog, items, purchase }: { listId: string; name: string; catalog: CatalogItem[]; items: ListItem[]; purchase: Purchase | null }) {
  const router = useRouter();
  const [selectedCatalogItemId, setSelectedCatalogItemId] = useState("");
  const [quantity, setQuantity] = useState("1");
  const [unit, setUnit] = useState<Unit>("kg");
  const [drafts, setDrafts] = useState<Record<string, { quantity: string; unit: Unit }>>({});
  const [message, setMessage] = useState<{ type: "success" | "error"; text: string } | null>(null);
  const [isPending, startTransition] = useTransition();
  const options = useMemo(() => catalog.map((item) => ({ value: item.id, label: item.name })), [catalog]);
  const text = shareText(name, items, purchase);
  function run(action: () => Promise<{ success: boolean; message: string }>) { startTransition(async () => { const result = await action(); setMessage({ type: result.success ? "success" : "error", text: result.message }); if (result.success) router.refresh(); }); }
  function addItem() { const parsedQuantity = Number(quantity); if (!selectedCatalogItemId || !Number.isFinite(parsedQuantity) || parsedQuantity <= 0) { setMessage({ type: "error", text: "Choose an item and enter a quantity greater than zero." }); return; } run(() => addEventGroceryItem({ listId, catalogItemId: selectedCatalogItemId, quantity: parsedQuantity, unit })); }
  function saveItem(item: ListItem) { const draft = drafts[item.id]; if (!draft) return; const parsedQuantity = Number(draft.quantity); if (!Number.isFinite(parsedQuantity) || parsedQuantity <= 0) { setMessage({ type: "error", text: "Quantity must be greater than zero." }); return; } run(() => updateEventGroceryItem(item.id, parsedQuantity, draft.unit)); }
  function orderOnline() { if (items.length === 0) { setMessage({ type: "error", text: "Add at least one grocery item before ordering." }); return; } startTransition(async () => { const result = await createEventGroceryCheckoutSession(listId); if (!result.success) { setMessage({ type: "error", text: result.message }); return; } router.push(`/dashboard/grocery/select-store?session=${encodeURIComponent(result.sessionId)}`); }); }
  async function copyList() { try { await navigator.clipboard.writeText(text); setMessage({ type: "success", text: "Formatted grocery list copied." }); } catch { setMessage({ type: "error", text: "Copy is unavailable in this browser." }); } }
  async function shareList() { if (navigator.share) { try { await navigator.share({ title: `${name} - Grocery List`, text }); return; } catch { return; } } await copyList(); }
  return <div className="space-y-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><Link href="/dashboard/event-grocery" className="text-sm font-medium text-emerald-300 hover:text-emerald-200">← Event Grocery Lists</Link><div className="mt-2 flex flex-wrap items-center gap-3"><h1 className="text-3xl font-semibold tracking-tight text-white">{name}</h1>{purchase ? <span className="rounded-full border border-emerald-300/30 bg-emerald-500/10 px-3 py-1 text-xs font-semibold uppercase tracking-wide text-emerald-200">✓ Purchased</span> : null}</div><p className="mt-2 text-sm text-zinc-400">A clean list for sharing, printing, and shopping together.</p>{purchase ? <div className="mt-4 flex flex-wrap gap-3 text-sm"><span className="rounded-xl border border-emerald-300/20 bg-emerald-500/[0.06] px-3 py-2 text-emerald-100">Purchased via <strong>{purchase.providerName}</strong></span><span className="rounded-xl border border-white/[0.08] bg-white/[0.04] px-3 py-2 text-zinc-300">{new Intl.DateTimeFormat("en-IN", { day: "numeric", month: "short", year: "numeric" }).format(new Date(purchase.completedAt))}</span><span className="rounded-xl border border-white/[0.08] bg-white/[0.04] px-3 py-2 text-zinc-300">{purchase.itemCount} item{purchase.itemCount === 1 ? "" : "s"} purchased</span></div> : null}</div><div className="flex flex-wrap gap-2"><button type="button" onClick={orderOnline} disabled={isPending || items.length === 0} className="inline-flex items-center gap-2 rounded-xl bg-emerald-400 px-4 py-2.5 text-sm font-semibold text-emerald-950 transition hover:bg-emerald-300 disabled:cursor-not-allowed disabled:opacity-60"><ShoppingCart className="h-4 w-4" aria-hidden="true" />{purchase ? "Order Again" : "Order Online"}</button><button type="button" onClick={shareList} className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-white/[0.04] px-4 py-2.5 text-sm font-semibold text-zinc-200 transition hover:bg-white/[0.08]"><Share2 className="h-4 w-4" aria-hidden="true" />Share List</button><button type="button" onClick={copyList} className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-white/[0.04] px-4 py-2.5 text-sm font-semibold text-zinc-200 transition hover:bg-white/[0.08]"><Copy className="h-4 w-4" aria-hidden="true" />Copy</button></div></div>
    {!purchase ? <section className="rounded-3xl border border-white/[0.08] bg-white/[0.04] p-5 sm:p-7 print:border-zinc-300 print:bg-white" aria-labelledby="add-event-item-heading"><h2 id="add-event-item-heading" className="text-xl font-semibold text-white print:text-zinc-900">Add Grocery Item</h2><div className="mt-5 grid gap-3 sm:grid-cols-[minmax(0,1fr)_7rem_8rem_auto]"><SearchableCombobox options={options} value={selectedCatalogItemId} onValueChange={setSelectedCatalogItemId} placeholder="Search grocery items..." searchPlaceholder="Search grocery items..." emptyMessage="No grocery item found." ariaLabel="Search event grocery items" /><input value={quantity} onChange={(event) => setQuantity(event.target.value)} type="number" min="0.001" step="0.001" aria-label="Quantity" className="rounded-xl border border-white/10 bg-black/20 px-3 py-3 text-white outline-none focus:border-emerald-400" /><select value={unit} onChange={(event) => setUnit(event.target.value as Unit)} aria-label="Unit" className="rounded-xl border border-white/10 bg-black/20 px-3 py-3 text-white outline-none focus:border-emerald-400">{units.map((value) => <option key={value} value={value}>{value}</option>)}</select><button type="button" onClick={addItem} disabled={isPending} className="inline-flex items-center justify-center gap-2 rounded-xl bg-emerald-400 px-5 py-3 font-semibold text-zinc-950 transition hover:bg-emerald-300 disabled:opacity-60"><Plus className="h-5 w-5" aria-hidden="true" />Add</button></div>{message ? <p className={`mt-4 flex items-center gap-2 text-sm ${message.type === "success" ? "text-emerald-300" : "text-rose-300"}`} role={message.type === "error" ? "alert" : "status"}>{message.type === "success" ? <CheckCircle2 className="h-4 w-4" aria-hidden="true" /> : null}{message.text}</p> : null}</section> : null}
    <section className="rounded-3xl border border-white/[0.08] bg-white/[0.04] p-5 sm:p-7 print:border-zinc-300 print:bg-white" aria-labelledby="event-items-heading"><div className="flex items-center justify-between gap-4"><div><h2 id="event-items-heading" className="text-xl font-semibold text-white print:text-zinc-900">Grocery Items</h2><p className="mt-1 text-sm text-zinc-400 print:text-zinc-600">{items.length} item{items.length === 1 ? "" : "s"}</p></div></div>{items.length === 0 ? <p className="mt-5 rounded-2xl border border-dashed border-white/10 px-4 py-10 text-center text-sm text-zinc-500">Add your first grocery item above.</p> : <ul className="mt-5 divide-y divide-white/[0.08] print:divide-zinc-200">{items.map((item) => { const draft = drafts[item.id] ?? { quantity: String(item.quantity), unit: item.unit }; return <li key={item.id} className="flex flex-col gap-3 py-4 sm:flex-row sm:items-center sm:justify-between"><p className="font-medium text-white print:text-zinc-900">{item.name}</p>{purchase ? <p className="text-sm font-medium text-emerald-200 print:text-zinc-800">{item.quantity} {item.unit}</p> : <><div className="flex items-center gap-2 print:hidden"><input aria-label={`Quantity for ${item.name}`} value={draft.quantity} onChange={(event) => setDrafts((current) => ({ ...current, [item.id]: { ...draft, quantity: event.target.value } }))} onBlur={() => saveItem(item)} type="number" min="0.001" step="0.001" className="w-24 rounded-xl border border-white/10 bg-black/20 px-3 py-2 text-right text-white outline-none focus:border-emerald-400" /><select aria-label={`Unit for ${item.name}`} value={draft.unit} onChange={(event) => { const next = { ...draft, unit: event.target.value as Unit }; setDrafts((current) => ({ ...current, [item.id]: next })); }} onBlur={() => saveItem(item)} className="rounded-xl border border-white/10 bg-black/20 px-2 py-2 text-white outline-none focus:border-emerald-400">{units.map((value) => <option key={value} value={value}>{value}</option>)}</select><button type="button" onClick={() => run(() => removeEventGroceryItem(item.id))} disabled={isPending} className="rounded-xl border border-rose-400/30 bg-rose-500/10 p-2 text-rose-200 transition hover:bg-rose-500/15" aria-label={`Remove ${item.name}`}><Trash2 className="h-4 w-4" aria-hidden="true" /></button></div><p className="hidden text-sm font-medium text-zinc-800 print:block">{item.quantity} {item.unit}</p></>}</li>; })}</ul>}</section></div>;
}
