"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import { ChefHat, CirclePlus, LoaderCircle, Search, Sparkles, Trash2 } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { Controller, useFieldArray, useForm } from "react-hook-form";

import ProfileField from "@/components/profile/ProfileField";
import MultiSelect from "@/components/ui/multi-select";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { createRecipe } from "@/lib/recipes/actions";
import { recipeFormSchema, type RecipeFormInput } from "@/lib/recipes/schemas";
import type { RecipeCatalogItem } from "@/lib/recipes/types";

type RecipeLibraryProps = {
  recipes: RecipeCatalogItem[];
  ingredients: { id: string; name: string; default_unit_code: string | null }[];
  mealCategories: { id: string; name: string }[];
  cuisines: { id: string; name: string }[];
  tags: { id: string; name: string; category: string }[];
  equipment: { id: string; name: string }[];
  initialSearch: string;
  authoring?: boolean;
};

const inputClassName = "w-full rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-white placeholder:text-zinc-500 outline-none transition focus:border-emerald-400 focus:ring-2 focus:ring-emerald-400/20";

const defaults: RecipeFormInput = {
  name: "", description: null, primary_cuisine_id: null, primary_cuisine_region_id: null, meal_category_ids: [], tag_ids: [], equipment_ids: [], servings: null, difficulty: null,
  prep_time_minutes: null, cook_time_minutes: null, calories_kcal: null, protein_g: null, carbohydrates_g: null, fat_g: null, fiber_g: null, sugar_g: null, sodium_mg: null,
  ingredients: [{ ingredient_id: "", quantity: 1, unit_code: "g", base_quantity: 1, base_unit_code: "g", is_optional: false, preparation_note: null }],
  steps: [{ instruction: "", estimated_duration_minutes: null, tip: null }],
};

export default function RecipeLibrary({ recipes, ingredients, mealCategories, cuisines, tags, equipment, initialSearch, authoring = false }: RecipeLibraryProps) {
  const router = useRouter();
  const [search, setSearch] = useState(initialSearch);
  const [message, setMessage] = useState<{ success: boolean; text: string } | null>(null);
  const { register, control, getValues, handleSubmit, reset, setValue, formState: { errors, isSubmitting } } = useForm<RecipeFormInput>({ resolver: zodResolver(recipeFormSchema), defaultValues: defaults });
  const ingredientFields = useFieldArray({ control, name: "ingredients" });
  const stepFields = useFieldArray({ control, name: "steps" });

  function searchCatalog(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    router.push(search.trim() ? `/dashboard/recipes?q=${encodeURIComponent(search.trim())}` : "/dashboard/recipes");
  }

  async function submit(values: RecipeFormInput) {
    setMessage(null);
    const result = await createRecipe(values);
    setMessage({ success: result.success, text: result.message });
    if (result.success) {
      reset(defaults);
      router.refresh();
    }
  }

  return <div className="space-y-6">
    <section className="flex flex-col gap-5 rounded-3xl border border-white/[0.08] bg-white/[0.04] p-6 backdrop-blur-xl lg:flex-row lg:items-center lg:justify-between">
      <div><p className="text-sm font-medium uppercase tracking-widest text-emerald-400/80">{authoring ? "My recipes" : "Global recipe library"}</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-white">{authoring ? "Add a private recipe" : "Recipes built for real weeks"}</h1><p className="mt-2 max-w-2xl text-sm leading-relaxed text-zinc-400">{authoring ? "Create a recipe using canonical ingredients for future planning, pantry, and grocery support." : "Quality-scored recipes use reusable ingredients, deterministic nutrition data, and planning-ready metadata."}</p></div>
      {!authoring ? <Link href="/dashboard/recipes/add" className="inline-flex items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-emerald-500 to-cyan-500 px-5 py-3 font-semibold text-white transition hover:scale-[1.02]"><CirclePlus className="h-5 w-5" aria-hidden="true" />Add recipe</Link> : null}
    </section>

    {authoring ? <section className="rounded-3xl border border-white/[0.08] bg-white/[0.04] p-5 sm:p-7"><div className="mb-6 flex items-center gap-3"><div className="rounded-xl bg-emerald-500/10 p-2 text-emerald-300"><ChefHat className="h-5 w-5" aria-hidden="true" /></div><div><h2 className="text-xl font-semibold text-white">Create a private recipe</h2><p className="text-sm text-zinc-400">Use canonical ingredients so planning, pantry, and grocery calculations stay connected.</p></div></div>
      <form className="space-y-8" noValidate onSubmit={handleSubmit(submit)}>
        <div className="grid gap-5 md:grid-cols-2"><ProfileField label="Recipe name" htmlFor="recipe_name" error={errors.name?.message}><input {...register("name")} id="recipe_name" className={inputClassName} placeholder="e.g. Vegetable pulao" /></ProfileField><ProfileField label="Cuisine" htmlFor="primary_cuisine_id" error={errors.primary_cuisine_id?.message}><Controller name="primary_cuisine_id" control={control} render={({ field }) => <Select value={field.value ?? undefined} onValueChange={field.onChange}><SelectTrigger id="primary_cuisine_id"><SelectValue placeholder="Optional cuisine" /></SelectTrigger><SelectContent>{cuisines.map((cuisine) => <SelectItem key={cuisine.id} value={cuisine.id}>{cuisine.name}</SelectItem>)}</SelectContent></Select>} /></ProfileField>
          <ProfileField label="Description" htmlFor="description" error={errors.description?.message}><input {...register("description", { setValueAs: (value: string) => value || null })} id="description" className={inputClassName} placeholder="A concise, helpful description" /></ProfileField><ProfileField label="Difficulty" htmlFor="difficulty" error={errors.difficulty?.message}><Controller name="difficulty" control={control} render={({ field }) => <Select value={field.value ?? undefined} onValueChange={field.onChange}><SelectTrigger id="difficulty"><SelectValue placeholder="Optional difficulty" /></SelectTrigger><SelectContent><SelectItem value="beginner">Beginner</SelectItem><SelectItem value="intermediate">Intermediate</SelectItem><SelectItem value="advanced">Advanced</SelectItem></SelectContent></Select>} /></ProfileField>
          <ProfileField label="Meal categories" htmlFor="meal_category_ids" error={errors.meal_category_ids?.message}><Controller name="meal_category_ids" control={control} render={({ field }) => <MultiSelect id="meal_category_ids" options={mealCategories.map((category) => ({ value: category.id, label: category.name }))} value={field.value} onValueChange={field.onChange} placeholder="Choose meal categories" />} /></ProfileField><ProfileField label="Tags" htmlFor="tag_ids" error={errors.tag_ids?.message}><Controller name="tag_ids" control={control} render={({ field }) => <MultiSelect id="tag_ids" options={tags.map((tag) => ({ value: tag.id, label: tag.name }))} value={field.value} onValueChange={field.onChange} placeholder="Choose suitability or workflow tags" />} /></ProfileField>
          <ProfileField label="Required equipment" htmlFor="equipment_ids" error={errors.equipment_ids?.message}><Controller name="equipment_ids" control={control} render={({ field }) => <MultiSelect id="equipment_ids" options={equipment.map((item) => ({ value: item.id, label: item.name }))} value={field.value} onValueChange={field.onChange} placeholder="Choose equipment" />} /></ProfileField><ProfileField label="Servings" htmlFor="servings" error={errors.servings?.message}><input {...register("servings", { setValueAs: (value: string) => value === "" ? null : Number(value) })} id="servings" type="number" min="0.5" step="0.5" className={inputClassName} /></ProfileField>
          <ProfileField label="Preparation minutes" htmlFor="prep_time_minutes" error={errors.prep_time_minutes?.message}><input {...register("prep_time_minutes", { setValueAs: (value: string) => value === "" ? null : Number(value) })} id="prep_time_minutes" type="number" min="0" className={inputClassName} /></ProfileField><ProfileField label="Cooking minutes" htmlFor="cook_time_minutes" error={errors.cook_time_minutes?.message}><input {...register("cook_time_minutes", { setValueAs: (value: string) => value === "" ? null : Number(value) })} id="cook_time_minutes" type="number" min="0" className={inputClassName} /></ProfileField></div>
        <fieldset><legend className="text-lg font-semibold text-white">Nutrition per serving</legend><p className="mt-1 text-sm text-zinc-400">Optional manual values. Verified catalog nutrition is managed separately.</p><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{([['calories_kcal', 'Calories'], ['protein_g', 'Protein (g)'], ['carbohydrates_g', 'Carbs (g)'], ['fat_g', 'Fat (g)'], ['fiber_g', 'Fiber (g)'], ['sugar_g', 'Sugar (g)'], ['sodium_mg', 'Sodium (mg)']] as const).map(([name, label]) => <ProfileField key={name} label={label} htmlFor={name} error={errors[name]?.message}><input {...register(name, { setValueAs: (value: string) => value === "" ? null : Number(value) })} id={name} type="number" min="0" step="0.1" className={inputClassName} /></ProfileField>)}</div></fieldset>
        <fieldset><div className="flex items-center justify-between gap-4"><div><legend className="text-lg font-semibold text-white">Ingredients</legend><p className="mt-1 text-sm text-zinc-400">Choose a catalog ingredient, then enter the amount and unit used in this recipe. Planning quantities are normalized automatically.</p></div><button type="button" onClick={() => ingredientFields.append({ ingredient_id: "", quantity: 1, unit_code: "g", base_quantity: 1, base_unit_code: "g", is_optional: false, preparation_note: null })} className="text-sm font-medium text-emerald-300 hover:text-emerald-200">Add ingredient</button></div><div className="mt-4 space-y-3">{ingredientFields.fields.map((field, index) => {
          const quantityField = register(`ingredients.${index}.quantity`, { valueAsNumber: true });
          const unitField = register(`ingredients.${index}.unit_code`);
          const syncBaseQuantity = (quantity: number, unitCode: string) => {
            const normalizedUnit = unitCode.trim();
            const canNormalize = Number.isFinite(quantity) && quantity > 0 && normalizedUnit.length > 0;
            setValue(`ingredients.${index}.base_quantity`, canNormalize ? quantity : null, { shouldValidate: true });
            setValue(`ingredients.${index}.base_unit_code`, canNormalize ? normalizedUnit : null, { shouldValidate: true });
          };
          return <div key={field.id} className="grid gap-3 rounded-2xl border border-white/[0.08] bg-black/10 p-4 lg:grid-cols-[2fr_0.7fr_0.7fr_1fr_auto]"><div><label className="mb-1.5 block text-xs font-medium text-zinc-300">Ingredient</label><Controller name={`ingredients.${index}.ingredient_id`} control={control} render={({ field: ingredientField }) => <Select value={ingredientField.value || undefined} onValueChange={(id) => { ingredientField.onChange(id); const ingredient = ingredients.find((item) => item.id === id); const unitCode = ingredient?.default_unit_code ?? getValues(`ingredients.${index}.unit_code`); if (ingredient?.default_unit_code) setValue(`ingredients.${index}.unit_code`, unitCode, { shouldValidate: true }); syncBaseQuantity(getValues(`ingredients.${index}.quantity`), unitCode); }}><SelectTrigger aria-label={`Ingredient ${index + 1}`}><SelectValue placeholder="Choose ingredient" /></SelectTrigger><SelectContent>{ingredients.map((ingredient) => <SelectItem key={ingredient.id} value={ingredient.id}>{ingredient.name}</SelectItem>)}</SelectContent></Select>} /></div><div><label className="mb-1.5 block text-xs font-medium text-zinc-300">Quantity</label><input {...quantityField} onChange={(event) => { quantityField.onChange(event); syncBaseQuantity(event.target.valueAsNumber, getValues(`ingredients.${index}.unit_code`)); }} type="number" min="0.001" step="0.001" aria-label={`Quantity for ingredient ${index + 1}`} className={inputClassName} /></div><div><label className="mb-1.5 block text-xs font-medium text-zinc-300">Unit</label><input {...unitField} onChange={(event) => { unitField.onChange(event); syncBaseQuantity(getValues(`ingredients.${index}.quantity`), event.target.value); }} aria-label={`Unit for ingredient ${index + 1}`} placeholder="e.g. g, ml, count" className={inputClassName} /></div><div><label className="mb-1.5 block text-xs font-medium text-zinc-300">Preparation <span className="text-zinc-500">(optional)</span></label><input {...register(`ingredients.${index}.preparation_note`, { setValueAs: (value: string) => value || null })} aria-label={`Preparation note for ingredient ${index + 1}`} placeholder="e.g. chopped" className={inputClassName} /></div><button type="button" onClick={() => ingredientFields.remove(index)} disabled={ingredientFields.fields.length === 1} className="mt-6 rounded-xl border border-white/10 px-3 text-zinc-400 hover:text-rose-300 disabled:opacity-40" aria-label="Remove ingredient"><Trash2 className="h-4 w-4" /></button>{errors.ingredients?.[index] ? <p className="lg:col-span-5 text-sm text-rose-400">{errors.ingredients[index]?.ingredient_id?.message ?? errors.ingredients[index]?.quantity?.message ?? errors.ingredients[index]?.unit_code?.message ?? errors.ingredients[index]?.base_unit_code?.message}</p> : null}</div>;
        })}</div></fieldset>
        <fieldset><div className="flex items-center justify-between gap-4"><div><legend className="text-lg font-semibold text-white">Cooking steps</legend><p className="mt-1 text-sm text-zinc-400">Keep steps ordered and practical.</p></div><button type="button" onClick={() => stepFields.append({ instruction: "", estimated_duration_minutes: null, tip: null })} className="text-sm font-medium text-emerald-300 hover:text-emerald-200">Add step</button></div><div className="mt-4 space-y-3">{stepFields.fields.map((field, index) => <div key={field.id} className="flex gap-3 rounded-2xl border border-white/[0.08] bg-black/10 p-4"><span className="mt-3 text-sm font-semibold text-emerald-300">{index + 1}</span><div className="grid flex-1 gap-3"><input {...register(`steps.${index}.instruction`)} aria-label={`Instruction for step ${index + 1}`} placeholder="Describe this step" className={inputClassName} /><div className="grid gap-3 sm:grid-cols-2"><input {...register(`steps.${index}.estimated_duration_minutes`, { setValueAs: (value: string) => value === "" ? null : Number(value) })} type="number" min="0" aria-label={`Minutes for step ${index + 1}`} placeholder="Estimated minutes" className={inputClassName} /><input {...register(`steps.${index}.tip`, { setValueAs: (value: string) => value || null })} aria-label={`Tip for step ${index + 1}`} placeholder="Optional tip" className={inputClassName} /></div>{errors.steps?.[index]?.instruction ? <p className="text-sm text-rose-400">{errors.steps[index]?.instruction?.message}</p> : null}</div><button type="button" onClick={() => stepFields.remove(index)} disabled={stepFields.fields.length === 1} className="self-start rounded-xl border border-white/10 p-3 text-zinc-400 hover:text-rose-300 disabled:opacity-40" aria-label="Remove step"><Trash2 className="h-4 w-4" /></button></div>)}</div></fieldset>
        <div className="flex flex-wrap items-center justify-between gap-4 border-t border-white/[0.08] pt-6">{message ? <p className={message.success ? "text-sm text-emerald-300" : "text-sm text-rose-400"} role={message.success ? "status" : "alert"}>{message.text}</p> : <span />}<button type="submit" disabled={isSubmitting} className="inline-flex items-center gap-2 rounded-xl bg-gradient-to-r from-emerald-500 to-cyan-500 px-5 py-3 font-semibold text-white disabled:cursor-not-allowed disabled:opacity-70">{isSubmitting ? <LoaderCircle className="h-5 w-5 animate-spin" /> : <ChefHat className="h-5 w-5" />}{isSubmitting ? "Saving recipe..." : "Save private recipe"}</button></div>
      </form></section> : null}

    {!authoring ? <section className="rounded-3xl border border-white/[0.08] bg-white/[0.04] p-5 sm:p-7"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-xl font-semibold text-white">Recipe catalog</h2><p className="mt-1 text-sm text-zinc-400">Browse curated recipes now; search and filters are ready for the growing catalog.</p></div><form onSubmit={searchCatalog} className="flex w-full gap-2 sm:max-w-md"><label className="sr-only" htmlFor="recipe-search">Search recipes</label><input id="recipe-search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search recipes" className={inputClassName} /><button className="rounded-xl border border-white/10 bg-white/5 px-4 text-emerald-300 hover:bg-emerald-500/10" aria-label="Search recipes"><Search className="h-5 w-5" /></button></form></div><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{recipes.map((recipe) => <article key={recipe.id} className="rounded-2xl border border-white/[0.08] bg-black/15 p-5"><div className="flex items-start justify-between gap-3"><h3 className="font-semibold text-white">{recipe.name}</h3><span className="inline-flex shrink-0 items-center gap-1 rounded-full bg-emerald-500/10 px-2.5 py-1 text-xs font-medium text-emerald-300"><Sparkles className="h-3.5 w-3.5" />{recipe.qualityScore}</span></div>{recipe.description ? <p className="mt-2 line-clamp-2 text-sm text-zinc-400">{recipe.description}</p> : null}<p className="mt-4 text-sm text-zinc-500">{recipe.total_time_minutes ? `${recipe.total_time_minutes} min` : "Time not set"}{recipe.servings ? ` · ${recipe.servings} servings` : ""}{recipe.estimated_cost !== null ? ` · ${recipe.estimated_cost_currency ?? "INR"} ${recipe.estimated_cost}` : ""}</p>{recipe.tags.length ? <div className="mt-4 flex flex-wrap gap-2">{recipe.tags.slice(0, 4).map((tag) => <span key={tag.id} className="rounded-full border border-white/10 px-2 py-1 text-xs text-zinc-300">{tag.name}</span>)}</div> : null}</article>)}{recipes.length === 0 ? <div className="md:col-span-2 xl:col-span-3 rounded-2xl border border-dashed border-white/10 px-6 py-12 text-center"><ChefHat className="mx-auto h-9 w-9 text-emerald-300" aria-hidden="true" /><h3 className="mt-4 text-lg font-semibold text-white">The curated recipe catalog is on its way</h3><p className="mx-auto mt-2 max-w-xl text-sm leading-relaxed text-zinc-400">Nutriweek is preparing a verified collection of planning-ready recipes. The catalog will be populated in the next milestone.</p><Link href="/dashboard/recipes/add" className="mt-5 inline-flex text-sm font-medium text-emerald-300 hover:text-emerald-200">Add your own private recipe in the meantime</Link></div> : null}</div></section> : null}
  </div>;
}
