insert into public.ingredients (slug, name, ingredient_category, default_unit_code) values
  ('rice', 'Rice', 'grains', 'g'),
  ('basmati-rice', 'Basmati Rice', 'grains', 'g'),
  ('sona-masoori-rice', 'Sona Masoori Rice', 'grains', 'g'),
  ('brown-rice', 'Brown Rice', 'grains', 'g'),
  ('poha', 'Poha', 'grains', 'g'),
  ('semolina', 'Semolina', 'grains', 'g'),
  ('whole-wheat-flour', 'Whole Wheat Flour', 'flours', 'g'),
  ('all-purpose-flour', 'All-Purpose Flour', 'flours', 'g'),
  ('besan', 'Besan', 'flours', 'g'),
  ('ragi-flour', 'Ragi Flour', 'flours', 'g'),
  ('jowar-flour', 'Jowar Flour', 'flours', 'g'),
  ('bajra-flour', 'Bajra Flour', 'flours', 'g'),
  ('oats', 'Oats', 'grains', 'g'),
  ('vermicelli', 'Vermicelli', 'grains', 'g'),
  ('idli-rice', 'Idli Rice', 'grains', 'g'),
  ('toor-dal', 'Toor Dal', 'pulses', 'g'),
  ('moong-dal', 'Moong Dal', 'pulses', 'g'),
  ('masoor-dal', 'Masoor Dal', 'pulses', 'g'),
  ('urad-dal', 'Urad Dal', 'pulses', 'g'),
  ('chana-dal', 'Chana Dal', 'pulses', 'g'),
  ('whole-chickpeas', 'Whole Chickpeas', 'pulses', 'g'),
  ('black-chickpeas', 'Black Chickpeas', 'pulses', 'g'),
  ('rajma', 'Rajma', 'pulses', 'g'),
  ('lobia', 'Lobia', 'pulses', 'g'),
  ('green-peas', 'Green Peas', 'vegetables', 'g'),
  ('potato', 'Potato', 'vegetables', 'g'),
  ('sweet-potato', 'Sweet Potato', 'vegetables', 'g'),
  ('onion', 'Onion', 'vegetables', 'g'),
  ('tomato', 'Tomato', 'vegetables', 'g'),
  ('ginger', 'Ginger', 'vegetables', 'g'),
  ('garlic', 'Garlic', 'vegetables', 'g'),
  ('green-chilli', 'Green Chilli', 'vegetables', 'g'),
  ('coriander-leaves', 'Coriander Leaves', 'herbs', 'g'),
  ('mint-leaves', 'Mint Leaves', 'herbs', 'g'),
  ('curry-leaves', 'Curry Leaves', 'herbs', 'g'),
  ('spinach', 'Spinach', 'vegetables', 'g'),
  ('fenugreek-leaves', 'Fenugreek Leaves', 'vegetables', 'g'),
  ('cabbage', 'Cabbage', 'vegetables', 'g'),
  ('cauliflower', 'Cauliflower', 'vegetables', 'g'),
  ('broccoli', 'Broccoli', 'vegetables', 'g'),
  ('carrot', 'Carrot', 'vegetables', 'g'),
  ('beetroot', 'Beetroot', 'vegetables', 'g'),
  ('beans', 'Green Beans', 'vegetables', 'g'),
  ('capsicum', 'Capsicum', 'vegetables', 'g'),
  ('bell-pepper', 'Bell Pepper', 'vegetables', 'g'),
  ('brinjal', 'Brinjal', 'vegetables', 'g'),
  ('okra', 'Okra', 'vegetables', 'g'),
  ('bottle-gourd', 'Bottle Gourd', 'vegetables', 'g'),
  ('ridge-gourd', 'Ridge Gourd', 'vegetables', 'g'),
  ('bitter-gourd', 'Bitter Gourd', 'vegetables', 'g'),
  ('ash-gourd', 'Ash Gourd', 'vegetables', 'g'),
  ('pumpkin', 'Pumpkin', 'vegetables', 'g'),
  ('zucchini', 'Zucchini', 'vegetables', 'g'),
  ('mushroom', 'Mushroom', 'vegetables', 'g'),
  ('cucumber', 'Cucumber', 'vegetables', 'g'),
  ('radish', 'Radish', 'vegetables', 'g'),
  ('turnip', 'Turnip', 'vegetables', 'g'),
  ('drumstick', 'Drumstick', 'vegetables', 'g'),
  ('raw-banana', 'Raw Banana', 'vegetables', 'g'),
  ('jackfruit', 'Raw Jackfruit', 'vegetables', 'g'),
  ('lemon', 'Lemon', 'fruits', 'g'),
  ('tamarind', 'Tamarind', 'condiments', 'g'),
  ('coconut', 'Coconut', 'condiments', 'g'),
  ('coconut-milk', 'Coconut Milk', 'dairy-alternatives', 'ml'),
  ('paneer', 'Paneer', 'dairy', 'g'),
  ('milk', 'Milk', 'dairy', 'ml'),
  ('curd', 'Curd', 'dairy', 'g'),
  ('yogurt', 'Yogurt', 'dairy', 'g'),
  ('ghee', 'Ghee', 'oils', 'ml'),
  ('butter', 'Butter', 'dairy', 'g'),
  ('cream', 'Cream', 'dairy', 'ml'),
  ('cheese', 'Cheese', 'dairy', 'g'),
  ('egg', 'Egg', 'eggs', 'count'),
  ('chicken', 'Chicken', 'meat', 'g'),
  ('mutton', 'Mutton', 'meat', 'g'),
  ('fish', 'Fish', 'seafood', 'g'),
  ('prawns', 'Prawns', 'seafood', 'g'),
  ('mustard-oil', 'Mustard Oil', 'oils', 'ml'),
  ('sunflower-oil', 'Sunflower Oil', 'oils', 'ml'),
  ('groundnut-oil', 'Groundnut Oil', 'oils', 'ml'),
  ('coconut-oil', 'Coconut Oil', 'oils', 'ml'),
  ('olive-oil', 'Olive Oil', 'oils', 'ml'),
  ('salt', 'Salt', 'seasonings', 'g'),
  ('sugar', 'Sugar', 'sweeteners', 'g'),
  ('jaggery', 'Jaggery', 'sweeteners', 'g'),
  ('turmeric', 'Turmeric', 'spices', 'g'),
  ('red-chilli-powder', 'Red Chilli Powder', 'spices', 'g'),
  ('coriander-powder', 'Coriander Powder', 'spices', 'g'),
  ('cumin-seeds', 'Cumin Seeds', 'spices', 'g'),
  ('cumin-powder', 'Cumin Powder', 'spices', 'g'),
  ('mustard-seeds', 'Mustard Seeds', 'spices', 'g'),
  ('fenugreek-seeds', 'Fenugreek Seeds', 'spices', 'g'),
  ('fennel-seeds', 'Fennel Seeds', 'spices', 'g'),
  ('carom-seeds', 'Carom Seeds', 'spices', 'g'),
  ('black-pepper', 'Black Pepper', 'spices', 'g'),
  ('cloves', 'Cloves', 'spices', 'g'),
  ('green-cardamom', 'Green Cardamom', 'spices', 'g'),
  ('cinnamon', 'Cinnamon', 'spices', 'g'),
  ('bay-leaf', 'Bay Leaf', 'spices', 'count'),
  ('asafoetida', 'Asafoetida', 'spices', 'g'),
  ('garam-masala', 'Garam Masala', 'spices', 'g'),
  ('sambar-powder', 'Sambar Powder', 'spices', 'g'),
  ('rasam-powder', 'Rasam Powder', 'spices', 'g'),
  ('kashmiri-chilli-powder', 'Kashmiri Chilli Powder', 'spices', 'g'),
  ('kasuri-methi', 'Kasuri Methi', 'spices', 'g'),
  ('black-salt', 'Black Salt', 'seasonings', 'g'),
  ('vinegar', 'Vinegar', 'condiments', 'ml'),
  ('soy-sauce', 'Soy Sauce', 'condiments', 'ml'),
  ('tomato-ketchup', 'Tomato Ketchup', 'condiments', 'ml'),
  ('peanuts', 'Peanuts', 'nuts', 'g'),
  ('cashews', 'Cashews', 'nuts', 'g'),
  ('almonds', 'Almonds', 'nuts', 'g'),
  ('raisins', 'Raisins', 'dried-fruits', 'g'),
  ('sesame-seeds', 'Sesame Seeds', 'seeds', 'g'),
  ('flax-seeds', 'Flax Seeds', 'seeds', 'g'),
  ('chia-seeds', 'Chia Seeds', 'seeds', 'g'),
  ('water', 'Water', 'basics', 'ml')
on conflict (slug) do nothing;

insert into public.ingredient_aliases (ingredient_id, normalized_name, display_name, locale)
select ingredients.id, aliases.normalized_name, aliases.display_name, aliases.locale
from (values
  ('coriander-leaves', 'coriander', 'Coriander', 'en'),
  ('coriander-leaves', 'dhania', 'Dhania', 'hi'),
  ('coriander-leaves', 'kothamalli', 'Kothamalli', 'ta'),
  ('brinjal', 'eggplant', 'Eggplant', 'en'),
  ('brinjal', 'baingan', 'Baingan', 'hi'),
  ('curd', 'dahi', 'Dahi', 'hi'),
  ('whole-chickpeas', 'chole', 'Chole', 'hi'),
  ('whole-chickpeas', 'kabuli-chana', 'Kabuli Chana', 'hi'),
  ('black-chickpeas', 'kala-chana', 'Kala Chana', 'hi'),
  ('capsicum', 'shimla-mirch', 'Shimla Mirch', 'hi')
) as aliases(ingredient_slug, normalized_name, display_name, locale)
join public.ingredients on ingredients.slug = aliases.ingredient_slug
on conflict (normalized_name) do nothing;
